blockExoticSubdeps: true
dangerouslyAllowAllBuilds: false
lockfile: true
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
preferFrozenLockfile: true
strictDepBuilds: true
strictStorePkgContentCheck: true
trustLockfile: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
verifyStoreIntegrity: true
