blockExoticSubdeps: true
dangerouslyAllowAllBuilds: false
lockfile: true
minimumReleaseAge: 2880
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
preferFrozenLockfile: true
strictDepBuilds: true
strictStorePkgContentCheck: true
trustLockfile: false
trustPolicy: no-downgrade
verifyStoreIntegrity: true
